### PR TITLE
Retile - Create STAC catalog

### PR DESCRIPTION
**Pull request by fnattino**

### CODE REVIEW

**Comment by fnattino** [comment]
Not sure whether we really want to make a real review of the notebooks. It might be handy to keep all of them in the same branch.

**Comment by meiertgrootes** [comment]
Hmm, you may be right. Although having branches would allow for notebooks in rougher states to be shared for discussion w/o the need to make clear that they are still very preliminary. they should all reside win the notebooks folder though.

The catalog demonstrator looks nice. I think the only thing I'd suggest we consider adding is links any useful STAC documentation, so that people can access that for reference on the schema etc.

**Review by meiertgrootes — APPROVED** [review]
See My comment in the conversation.

**Comment by fnattino** [comment]
Thanks a lot @meiertgrootes , you are definitely right, I have added some links to the relevant documentation!

**Pull request closed without merging**
